import { AiApiEndpoint } from "./types";
import { upsertEndpoint } from "./storage/db";

/**
 * Known popular free AI API endpoints.
 * Used to seed the database so users have data immediately,
 * before running the scrapers.
 */
export function seedKnownApis(): number {
  const endpoints: Array<Partial<AiApiEndpoint>> = [
    // ===== Text Generation =====
    {
      name: "OpenAI API",
      url: "https://api.openai.com/v1/chat/completions",
      description: "ChatGPT models: GPT-4o, GPT-4o-mini, GPT-4. Free tier credits for new users.",
      category: "text-generation",
      provider: "OpenAI",
      requiresAuth: true,
      authNote: "API key required — free credits for new signups",
      status: "active",
      source: "seed",
      tags: ["free-tier", "chat", "gpt-4o", "official"],
    },
    {
      name: "Google Gemini API",
      url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent",
      description: "Gemini 1.5 Flash & Pro. Generous free tier for personal/prototyping use.",
      category: "text-generation",
      provider: "Google",
      requiresAuth: true,
      authNote: "API key required — free tier available",
      status: "active",
      source: "seed",
      tags: ["free-tier", "multimodal", "gemini"],
    },
    {
      name: "Groq API",
      url: "https://api.groq.com/openai/v1/chat/completions",
      description: "Ultra-fast inference for Llama 3, Mixtral, Gemma. OpenAI-compatible API.",
      category: "text-generation",
      provider: "Groq",
      requiresAuth: true,
      authNote: "API key required — free tier available",
      status: "active",
      source: "seed",
      tags: ["fast", "llama-3", "openai-compatible"],
    },
    {
      name: "Mistral AI API",
      url: "https://api.mistral.ai/v1/chat/completions",
      description: "Mistral 7B, Mixtral, Codestral. OpenAI-compatible chat completions.",
      category: "text-generation",
      provider: "Mistral AI",
      requiresAuth: true,
      authNote: "API key required — free tier available",
      status: "active",
      source: "seed",
      tags: ["free-tier", "mistral", "openai-compatible"],
    },
    {
      name: "Hugging Face Inference API",
      url: "https://api-inference.huggingface.co/models/",
      description: "Free inference for thousands of open models (transformers, diffusers, etc.).",
      category: "text-generation",
      provider: "Hugging Face",
      requiresAuth: true,
      authNote: "API key required — free tier with rate limits",
      status: "active",
      source: "seed",
      tags: ["free-tier", "open-models", "rate-limited"],
    },
    {
      name: "Together AI",
      url: "https://api.together.xyz/v1/chat/completions",
      description: "Many open models: Llama 3, Mixtral, Qwen, etc. Free credits on signup.",
      category: "text-generation",
      provider: "Together AI",
      requiresAuth: true,
      authNote: "API key required — free credits on signup",
      status: "active",
      source: "seed",
      tags: ["free-tier", "open-models", "credits"],
    },
    {
      name: "DeepInfra",
      url: "https://api.deepinfra.com/v1/openai/chat/completions",
      description: "Open models inference (Llama 3, Mixtral, Whisper). Pay-as-you-go, cheap.",
      category: "text-generation",
      provider: "DeepInfra",
      requiresAuth: true,
      authNote: "API key required",
      status: "active",
      source: "seed",
      tags: ["open-models", "cheap"],
    },
    {
      name: "Cohere API",
      url: "https://api.cohere.ai/v1/chat",
      description: "Command R models for chat and RAG. Free trial tier.",
      category: "text-generation",
      provider: "Cohere",
      requiresAuth: true,
      authNote: "API key required — free trial tier",
      status: "active",
      source: "seed",
      tags: ["free-tier", "command-r", "rag"],
    },
    {
      name: "AI21 Labs API",
      url: "https://api.ai21.com/studio/v1/chat/",
      description: "Jamba models. Free tier with API key.",
      category: "text-generation",
      provider: "AI21",
      requiresAuth: true,
      authNote: "API key required — free tier available",
      status: "active",
      source: "seed",
      tags: ["free-tier", "jamba"],
    },
    {
      name: "Perplexity API",
      url: "https://api.perplexity.ai/chat/completions",
      description: "Perplexity online LLM (GPT-4, Claude, Sonar). $5 free credit.",
      category: "text-generation",
      provider: "Perplexity",
      requiresAuth: true,
      authNote: "API key required — $5 free credit",
      status: "active",
      source: "seed",
      tags: ["free-credit", "online-search"],
    },
    {
      name: "Anthropic Claude API",
      url: "https://api.anthropic.com/v1/messages",
      description: "Claude 3.5 Sonnet & Haiku. Free credits for new users.",
      category: "text-generation",
      provider: "Anthropic",
      requiresAuth: true,
      authNote: "API key required — free credits for new users",
      status: "active",
      source: "seed",
      tags: ["free-credit", "claude"],
    },
    {
      name: "Pollinations AI",
      url: "https://text.pollinations.ai/",
      description: "Completely FREE text generation API. No key required. Great for demos.",
      category: "text-generation",
      provider: "Pollinations",
      requiresAuth: false,
      authNote: "No API key required",
      status: "active",
      source: "seed",
      tags: ["free", "no-auth", "demos"],
    },

    // ===== Image Generation =====
    {
      name: "Pollinations Image API",
      url: "https://image.pollinations.ai/prompt/",
      description: "Completely FREE image generation (Stable Diffusion). No key required.",
      category: "image-generation",
      provider: "Pollinations",
      requiresAuth: false,
      authNote: "No API key required",
      status: "active",
      source: "seed",
      tags: ["free", "no-auth", "stable-diffusion"],
    },
    {
      name: "Replicate API",
      url: "https://api.replicate.com/v1/predictions",
      description: "Hosted open models: SDXL, Flux, Whisper, Llama, etc. Small free credits.",
      category: "image-generation",
      provider: "Replicate",
      requiresAuth: true,
      authNote: "API key required — small free credits on signup",
      status: "active",
      source: "seed",
      tags: ["open-models", "credits"],
    },
    {
      name: "Stability AI API",
      url: "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
      description: "Stable Diffusion XL official API. Free tier available.",
      category: "image-generation",
      provider: "Stability AI",
      requiresAuth: true,
      authNote: "API key required — free tier",
      status: "active",
      source: "seed",
      tags: ["free-tier", "stable-diffusion"],
    },

    // ===== Audio / TTS / STT =====
    {
      name: "OpenAI Whisper API",
      url: "https://api.openai.com/v1/audio/transcriptions",
      description: "Speech-to-text via Whisper. Free tier credits.",
      category: "audio-tts-stt",
      provider: "OpenAI",
      requiresAuth: true,
      authNote: "API key required — free credits for new users",
      status: "active",
      source: "seed",
      tags: ["whisper", "stt"],
    },
    {
      name: "Hugging Face TTS Models",
      url: "https://api-inference.huggingface.co/models/suno/bark",
      description: "Free TTS/STT inference with open models (Bark, Whisper, etc.). Rate limited.",
      category: "audio-tts-stt",
      provider: "Hugging Face",
      requiresAuth: true,
      authNote: "API key required — free tier with rate limits",
      status: "active",
      source: "seed",
      tags: ["tts", "stt", "rate-limited"],
    },

    // ===== Embeddings =====
    {
      name: "OpenAI Embeddings API",
      url: "https://api.openai.com/v1/embeddings",
      description: "text-embedding-3-small & text-embedding-ada-002. Free tier credits.",
      category: "embeddings",
      provider: "OpenAI",
      requiresAuth: true,
      authNote: "API key required",
      status: "active",
      source: "seed",
      tags: ["text-embedding", "vector"],
    },
    {
      name: "Cohere Embed API",
      url: "https://api.cohere.ai/v1/embed",
      description: "Cohere embed models. Free trial tier.",
      category: "embeddings",
      provider: "Cohere",
      requiresAuth: true,
      authNote: "API key required — free trial tier",
      status: "active",
      source: "seed",
      tags: ["text-embedding", "vector"],
    },
    {
      name: "Google Gemini Embeddings",
      url: "https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent",
      description: "Gemini text embeddings. Free tier available.",
      category: "embeddings",
      provider: "Google",
      requiresAuth: true,
      authNote: "API key required — free tier available",
      status: "active",
      source: "seed",
      tags: ["text-embedding", "vector"],
    },

    // ===== Translation =====
    {
      name: "Google Cloud Translation API",
      url: "https://translation.googleapis.com/language/translate/v2",
      description: "Translate text in 100+ languages. Free tier: 500K chars/month.",
      category: "translation",
      provider: "Google",
      requiresAuth: true,
      authNote: "API key required — 500K chars/month free",
      status: "active",
      source: "seed",
      tags: ["free-tier", "100-languages"],
    },
    {
      name: "MyMemory Translation API",
      url: "https://api.mymemory.translated.net/get",
      description: "Free machine translation API. No key required. Rate limited.",
      category: "translation",
      provider: "MyMemory",
      requiresAuth: false,
      authNote: "No API key required — rate limited",
      status: "active",
      source: "seed",
      tags: ["free", "no-auth", "rate-limited"],
    },
    {
      name: "LibreTranslate",
      url: "https://libretranslate.com/translate",
      description: "Free and open-source translation API. Public instance available.",
      category: "translation",
      provider: "LibreTranslate",
      requiresAuth: true,
      authNote: "API key required for public instance — can self-host for free",
      status: "active",
      source: "seed",
      tags: ["open-source", "self-hosted"],
    },

    // ===== Search / RAG =====
    {
      name: "Serper.dev API",
      url: "https://google.serper.dev/search",
      description: "Google Search API for RAG. 2500 free queries.",
      category: "search-rag",
      provider: "Serper",
      requiresAuth: true,
      authNote: "API key required — 2500 free queries",
      status: "active",
      source: "seed",
      tags: ["free-tier", "google-search"],
    },
    {
      name: "Tavily Search API",
      url: "https://api.tavily.com/search",
      description: "AI-optimized search API for RAG agents. 1000 free credits/month.",
      category: "search-rag",
      provider: "Tavily",
      requiresAuth: true,
      authNote: "API key required — 1000 free credits/month",
      status: "active",
      source: "seed",
      tags: ["free-tier", "rag"],
    },
    {
      name: "Bing Web Search API",
      url: "https://api.bing.microsoft.com/v7.0/search",
      description: "Free tier: 1000 transactions/month.",
      category: "search-rag",
      provider: "Microsoft",
      requiresAuth: true,
      authNote: "API key required — 1000 transactions/month free",
      status: "active",
      source: "seed",
      tags: ["free-tier", "web-search"],
    },

    // ===== Other =====
    {
      name: "Hugging Face Inference (all tasks)",
      url: "https://router.huggingface.co/hf-inference/models/",
      description: "HF Inference Router covers text, image, audio, embedding models.",
      category: "other",
      provider: "Hugging Face",
      requiresAuth: true,
      authNote: "API key required",
      status: "active",
      source: "seed",
      tags: ["all-tasks", "open-models"],
    },
    {
      name: "Pollinations AI (multi-modal)",
      url: "https://image.pollinations.ai/",
      description: "Free multi-modal AI playground: text, image, audio generation.",
      category: "other",
      provider: "Pollinations",
      requiresAuth: false,
      authNote: "No API key required — donation supported",
      status: "active",
      source: "seed",
      tags: ["free", "no-auth", "multi-modal"],
    },
  ];

  let count = 0;
  for (const ep of endpoints) {
    upsertEndpoint({
      name: ep.name!,
      url: ep.url!,
      description: ep.description || "",
      category: (ep.category as any) || "other",
      provider: ep.provider || "",
      requiresAuth: !!ep.requiresAuth,
      authNote: ep.authNote || undefined,
      status: ep.status || "unknown",
      source: ep.source || "seed",
      tags: ep.tags || [],
    });
    count++;
  }

  return count;
}